# Remove these configuration records
# one by one as the offenses are removed from the code base.

# Offense count: 24
Metrics/AbcSize:
  Max: 75

# Offense count: 8
Metrics/CyclomaticComplexity:
  Max: 17

# Offense count: 12
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 88

# Offense count: 1
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 7

# Offense count: 7
Metrics/PerceivedComplexity:
  Max: 17

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: prefer_alias, prefer_alias_method
Style/Alias:
  Exclude:
    - 'lib/graph_matching/ordered_set.rb'

# Offense count: 4
Style/AsciiComments:
  Exclude:
    - 'lib/graph_matching/algorithm/mwm_bipartite.rb'
    - 'lib/graph_matching/algorithm/mwm_general.rb'

# Offense count: 18
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ProceduralMethods, FunctionalMethods, IgnoredMethods.
# SupportedStyles: line_count_based, semantic, braces_for_chaining
# ProceduralMethods: benchmark, bm, bmbm, create, each_with_object, measure, new, realtime, tap, with_object
# FunctionalMethods: let, let!, subject, watch
# IgnoredMethods: lambda, proc, it
Style/BlockDelimiters:
  Exclude:
    - 'benchmark/mwm_general/incomplete_graphs/benchmark.rb'
    - 'lib/graph_matching/algorithm/mcm_bipartite.rb'
    - 'lib/graph_matching/algorithm/mwm_bipartite.rb'
    - 'lib/graph_matching/algorithm/mwm_general.rb'
    - 'lib/graph_matching/graph/graph.rb'
    - 'lib/graph_matching/matching.rb'
    - 'lib/graph_matching/ordered_set.rb'
    - 'spec/graph_matching/algorithm/mcm_bipartite_spec.rb'

# Offense count: 7
# Cop supports --auto-correct.
Style/CommentIndentation:
  Exclude:
    - 'lib/graph_matching/algorithm/mcm_general.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, SingleLineConditionsOnly, IncludeTernaryExpressions.
# SupportedStyles: assign_to_condition, assign_inside_condition
Style/ConditionalAssignment:
  Exclude:
    - 'lib/graph_matching/algorithm/mwm_general.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: empty, nil, both
Style/EmptyElse:
  Exclude:
    - 'lib/graph_matching/algorithm/mwm_general.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/EmptyLineAfterMagicComment:
  Exclude:
    - 'graph_matching.gemspec'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: empty_lines, no_empty_lines
Style/EmptyLinesAroundBlockBody:
  Exclude:
    - 'lib/graph_matching/algorithm/mcm_general.rb'

# Offense count: 6
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: empty_lines, empty_lines_except_namespace, empty_lines_special, no_empty_lines
Style/EmptyLinesAroundClassBody:
  Exclude:
    - 'lib/graph_matching/algorithm/mcm_bipartite.rb'
    - 'lib/graph_matching/algorithm/mcm_general.rb'
    - 'lib/graph_matching/algorithm/mwm_bipartite.rb'
    - 'lib/graph_matching/algorithm/mwm_general.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/EmptyLinesAroundMethodBody:
  Exclude:
    - 'lib/graph_matching/algorithm/mcm_general.rb'

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: empty_lines, empty_lines_except_namespace, empty_lines_special, no_empty_lines
Style/EmptyLinesAroundModuleBody:
  Exclude:
    - 'lib/graph_matching/algorithm/matching_algorithm.rb'
    - 'lib/graph_matching/algorithm/mcm_bipartite.rb'
    - 'lib/graph_matching/algorithm/mcm_general.rb'
    - 'lib/graph_matching/algorithm/mwm_bipartite.rb'
    - 'lib/graph_matching/algorithm/mwm_general.rb'

# Offense count: 5
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: format, sprintf, percent
Style/FormatString:
  Exclude:
    - 'benchmark/mcm_bipartite/complete_bigraphs/benchmark.rb'
    - 'benchmark/mcm_general/complete_graphs/benchmark.rb'
    - 'benchmark/mwm_bipartite/complete_bigraphs/benchmark.rb'
    - 'benchmark/mwm_general/complete_graphs/benchmark.rb'
    - 'benchmark/mwm_general/incomplete_graphs/benchmark.rb'

# Offense count: 16
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'lib/graph_matching/algorithm/mcm_bipartite.rb'
    - 'lib/graph_matching/algorithm/mcm_general.rb'
    - 'lib/graph_matching/algorithm/mwm_bipartite.rb'
    - 'lib/graph_matching/algorithm/mwm_general.rb'
    - 'lib/graph_matching/algorithm/mwmg_delta_assertions.rb'
    - 'lib/graph_matching/assertion.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: auto_detection, squiggly, active_support, powerpack, unindent
Style/IndentHeredoc:
  Exclude:
    - 'lib/graph_matching/errors.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Exclude:
    - 'lib/graph_matching/algorithm/mwm_general.rb'
    - 'spec/graph_matching/integer_vertexes_spec.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets
